export interface MetricsResponse {
  "connection-creation-total": number;
  "response-rate": number;
  "select-rate": number;
  "connection-close-total": number;
  "start-time-ms": number;
  "network-io-rate": number;
  "io-ratio": number;
  "io-time-ns-total": number;
  "request-total": number;
  "successful-reauthentication-rate": number;
  "io-wait-ratio": number;
  "outgoing-byte-rate": number;
  "request-size-max": number;
  "successful-authentication-rate": number;
  "failed-authentication-rate": number;
  "network-io-total": number;
  "incoming-byte-total": number;
  "response-total": number;
  "failed-reauthentication-rate": number;
  "incoming-byte-rate": number;
  "io-wait-time-ns-total": number;
  "connection-close-rate": number;
  "request-size-avg": number;
  "iotime-total": number;
  "connection-creation-rate": number;
  "successful-authentication-total": number;
  "request-latency-avg": number | null;
  "connection-count": number;
  "successful-authentication-no-reauth-total": number;
  "count": number;
  "io-waittime-total": number;
  "io-wait-time-ns-avg": number;
  "reauthentication-latency-max": number | null;
  "commit-id": string;
  "version": string;
  "failed-authentication-total": number;
  "io-time-ns-avg": number;
  "failed-reauthentication-total": number;
  "request-rate": number;
  "request-latency-max": number | null;
  "select-total": number;
  "successful-reauthentication-total": number;
  "outgoing-byte-total": number;
  "reauthentication-latency-avg": number | null;
}